### ISSUE TITLE
Scaffolding and patching with Supernova contigs

### ISSUE THREAD

**Issue by francicco** [bcgsc/RAILS#12] opened 2019-06-13 21:28 UTC
Hi,

I'm reading the description of RAILS (RAILS and Cobbler:  Scaffolding and automated finishing of draft genomes using long DNA sequences). From what I understood "Cobbler and RAILS [...] can be used to scaffold & finish high-quality draft genome assemblies with any long, preferably high-quality, sequences such as scaftigs/contigs from another genome draft."

For a bunch of genomes, I have data produced with PacBio and 10X, for both, I have assembled a draft genome, and so far I'm using 10X data to error correct the PacBio draft and subsequently to further scaffold it using ARCS. Giving that both drafts have different completeness (BUSCO profiles), can I use RAILS to patch the PacBio genomes with the Supernova assembly?

Thank you,
F

**Comment by warrenlr** [comment] 2019-06-13 22:11
You certainly can do that (ie. use RAILS to scaffold and patch gaps with the supernova assembly).

That said, because the supernova assembly is likely very contiguous, I recommend breaking it into overlapping 2.5, 5, and 10kbp tiles and feeding it all to cobbler/RAILS to patch gaps in your pacbio genome assembly (similar to what I showed  in the RAILS paper, with the human example where I made overlapping sequence tiles of  1, 2.5, 5 & 15 kbp from the reference).

**Comment by francicco** [comment] 2019-06-13 22:53
Hi René,

Thanks for your answer. Is there any script doing that out there?

When would you suggest to run this, after or before the ARCS scaffolding?

Thanks again for your help.

**Comment by warrenlr** [comment] 2019-06-14 00:51
We typically run cobbler/RAILS before tigmint/ARCS, Sealer and ntEdit, but since Cobbler/RAILS are also gap-filling tools, you could also run after ARCS. We like the former order, because any misassemblies induced by scaffolding with long reads and detected by tigmint (from using linked reads) get corrected.

As for generating tiles:

1. I suggest breaking the assembly at Ns first (unless you don't mind patching gaps with Ns from another assembly.

To do this:
```
cat SUPERNOVA_WGA.fa | perl -ne 'if(/^\>/){$scafnum++;}else{my $len=length($_);my @scaftigs=split(/N+/i,$_);my $scaftignum=0;foreach my $scaftig(@scaftigs){ my $len=length($scaftig);$scaftignum++;  print ">wga$scafnum";print "."; print "$scaftignum,$len\n$scaftig\n";}}' > SUPERNOVA_SCAFTIGS.fa
```


2. Generate tiles (overlapping or not) from an assembly, using perl one-liners:

```
cat SUPERNOVA_SCAFTIGS.fa |perl -ne 'chomp;$set=2500;if(/\>(\S+)/){$h=$1;}else{ $seq=$_;$ct=0;for(my $x=1;$x<=length($seq);$x+=($set/2)){$ct++;$newseq=substr($seq,$x,$set);print ">$h-$ct\n$newseq\n" if(length($newseq)==$set);   }         }' > tiles2500.fa
cat SUPERNOVA_SCAFTIGS.fa |perl -ne 'chomp;$set=5000;if(/\>(\S+)/){$h=$1;}else{ $seq=$_;$ct=0;for(my $x=1;$x<=length($seq);$x+=($set/2)){$ct++;$newseq=substr($seq,$x,$set);print ">$h-$ct\n$newseq\n" if(length($newseq)==$set);   }         }' > tiles5000.fa
cat SUPERNOVA_SCAFTIGS.fa |perl -ne 'chomp;$set=10000;if(/\>(\S+)/){$h=$1;}else{ $seq=$_;$ct=0;for(my $x=1;$x<=length($seq);$x+=($set/2)){$ct++;$newseq=substr($seq,$x,$set);print ">$h-$ct\n$newseq\n" if(length($newseq)==$set);   }         }' > tiles10000.fa
cat tiles2500.fa tiles5000.fa tiles10000.fa > allTiles.fa
```

From the above scripts, all tiles are overlapping by half of the tile length.  If you want regular side-by-side tiles, change the one liner with:

```
cat SUPERNOVA_SCAFTIGS.fa |perl -ne 'chomp;$set=2500;if(/\>(\S+)/){$h=$1;}else{ $seq=$_;$ct=0;for(my $x=1;$x<=length($seq);$x+=$set){$ct++;$newseq=substr($seq,$x,$set);print ">$h-$ct\n$newseq\n" if(length($newseq)==$set);   }         }' > tiles2500no-overlap.fa
```

cheers
Rene

**Comment by francicco** [comment] 2019-06-14 10:08
Many thanks @warrenlr,

I'll give it a go!

F

**Comment by darencard** [comment] 2019-06-18 21:15
I have a related follow-up question that basically boils down to understanding the ecosystem of tools you have created and how to best stitch them together. Sorry in advance for a lengthly post. I'm primarily interested in the scaffolding, gapfilling, and polishing steps of genome assembly. My understanding based on [this page](http://www.birollab.ca/software) is the following:

1. Scaffolding
a. ARCS/ARKS - scaffolding based on linked reads (so short reads are mapped to the genome in some way)
b. LINKS - scaffolding with long, error-prone sequences (PacBio/Oxford Nanopore)
c. RAILS - scaffolding with long sequences (not necessarily error-prone?)

2. Gapfilling
a. cobbler - gapfilling with long reads (presumably they need to be high quality to avoid genome errors)
b. Sealer - gapfilling (presumably with short reads?)

3. Polishing
a. ntEdit - scalable polishing based on standard Illumina reads
b. Tigmint - corrects misassembly using linked Illumina reads (i.e., 10X Chromium)

So there is some apparent redundancy in some of these steps. The distinction with scaffolding appears to be whether one maps short reads (that are linked by barcodes; ARCS/ARKS) or long reads/sequences and whether the long reads have high error rates (LINKS) or low/no errors (RAILS). Of course, one could construct high-quality long sequences by error-correcting PacBio reads with Illumina or using Konnector to create pseudo-long reads with Illumina - the prerequisite is that the error rate is low and the sequences are long when using RAILS (first assumption is relaxed with LINKS). Is that understanding correct?

With gapfilling, the distinction is again between long and short sequences, with cobbler being designed for the former and Sealer (part of Abyss) for the latter. Is that understanding correct? I did see that Sealer is used with long sequences in the Beluga whale genome paper as well, so I'm more confused about the distinction between these two tools. 

I'm interested in using linked reads from 10X Chromium for gapfilling after scaffolding an existing Supernova assembly with Hi-C data, which appears to be a use-case that is not yet covered by existing tools (though please correct me if I'm wrong). My plan is to try to hack something together for this, which is why I'm trying to understand the tools available.

With the polishing step, everything should be high quality or it isn't very useful in polishing. There again seems to be a distinction between whether one is using linked reads (Tigmint) or standard Illumina reads (ntEdit). Do I have that right as well?

Any confirmations or clarifications are greatly appreciated! Sorry for a somewhat naive question, but just trying to distill the papers and tool documentation pages down into a flow-chart-like format.

Thanks in advance for the help!
Daren

**Comment by francicco** [comment] 2019-06-18 21:27
Hi @darencard,

I'm questioning as well which tool use and when. I extensively thought about the best pipeline and I figure out a way, but I'd like to know what @warrenlr thinks about that.

Cheers
F

**Comment by warrenlr** [comment] 2019-06-18 22:10
![image](https://user-images.githubusercontent.com/5719157/59723334-2c620f00-91db-11e9-9ff3-9f1dd7f9418b.png)

**Comment by francicco** [comment] 2019-06-18 22:11
What is the gray circle? I used Sealer with 10x data. Was I doing wrong?
F

**Comment by francicco** [comment] 2019-06-18 22:12
Oh, by the way using supernova scaffolds with RAILS did not produce any improvements. 
F

**Comment by warrenlr** [comment] 2019-06-18 22:36
hello both,

The tools are not necessarily run in the order shown in the image.

The type of sequence data you have (and the amount) generally dictates which tool and their order. Of course, a highly repeated genome may also influence your initial choice of sequencing technology (short vs. long read)

For instance, you may have high coverage from linked reads and shallow long read coverage.
In that case, I would recommend using supernova first, then LINKS (with shallow long reads) and/or cobblerRAILS (Because cobbler can close the gaps induced by LINKS).  I would then run tigmint+ARCS to correct and scaffold the assembly with linked reads and run sealer to close gaps.  Sealer can work with any accurate read data, since it builds a de Bruijn graph (out of kmers derived from the reads).  In reality, you can run Sealer several times, not necessarily only at the end, since closing gaps may help subsequent scaffolding steps (which is why some pipelines do not look simple).

Cobbler is designed to work with long sequences and uses that long-range info, whereas Sealer breaks sequences into words of size k (kmers) for building an implicit DBG using a Bloom filter.  This is why we use both in our pipelines, when we have both short and long reads (and yes, you may use linked reads with Sealer/ntEdit). The grey circle indicate that you can use that data for this application, although the application does not make use of the additional information (eg. long range information) the sequencing data type provides.

Your synopsis and understanding is correct, it is best to use cobbler/RAILS with accurate long sequences since it uses these sequences for gap-filling. LINKS was designed when nanopore read error was high and error correction methods was still in its infancy.  It is still very relevant today, since you can scaffold (without gap-filling) with erroneous long reads -- and the kmer-pair matching paradigm allows the users to run it iteratively, in a more flexible manner than alignment-based methods.  This could explain why the gains are lower when scaffolding with RAILS but @francicco, it could also be due to parameterization, long read coverage, already contiguous draft, etc.

Finally, tigmint uses locality info of linked reads to identify and break misassemblies in your draft, whereas ntedit is a fast genome polishing tool. For the latter, I recommend using accurate short reads (Illumina, linked reads) to polish any draft genomes you have.. and yes, the more accurate the consensus, the best the end result.

Hope it helps!
Rene

**Comment by francicco** [comment] 2019-06-18 22:49
Thank you Rene!

That was very reassuring and that exactly how I understood the algorithm, more or less. I have many genomes to assemble, and more or less each one of that has a slightly different configuration in terms of data type and data results; so it's really hard to have a common procedure.

**Comment by francicco** [comment] 2019-06-18 23:00
Thank you Rene!

That was very reassuring and that exactly how I understood the algorithm, more or less. I have many genomes to assemble, and more or less each one of that has a slightly different configuration in terms of data type and data results; so it's really hard to have a common procedure.

Generally I'm using tigmint to correct the first draft coming from the assembler; therefore corrected reads (CANU) with LINKS to run the first scaffolding followed by ARCS, the filling the gap with Long corrected reads and then shorts. I'm not sure now if I should run again tigmint to possibly correct errors introduced by the scaffolding and gap filling. I think I'll give it a go to have a measure of how the assembly is consistent, I was also thinking to use REAPR and/or NucBreak to do the same job.

About the polishing I'm very paranoid so I run it twice. The first time after the assembly is done, before tigmint and secondly after the gap filling. I'm using Pilon and I run 5 iteration correcting snps and indels. If I have also RNAseq data I run on top the 5 iterations, 3 more iterations only to correct indels.

Does it all make sense?

Best,
F

**Comment by warrenlr** [comment] 2019-06-19 01:57
I think tigmint + ARKS + sealer + polishing (pilon/ntedit)

should be your last steps (if you have linked reads).  That's because :
1. long read scaffolding could introduce misassemblies, which would be corrected with linked reads
2. ARCS/ARKS yield higher contiguity when the input draft is more contiguous 

yes, what you describe makes sense and is defendable in a research study.

**Comment by darencard** [comment] 2019-06-19 02:52
Thanks so much for the useful information @warrenlr! I have been brainstorming an approach to leverage the long-range information in the 10X data when gapfilling. I have come up with a couple of potential ways of doing this and was hoping to get some feedback on regarding feasibility.

1. Perform local assemblies of molecules based on matching Chromium barcodes to produce (hopefully) long reads, which can be fed into cobbler.

2. Perform gapfilling based on short reads using Sealer. As you say, Sealer does not natively support long-range/barcode info from the Chromium data.

With both approaches, I was thinking I could use 10X's longranger software, which takes Chromium barcodes into account, to map 10X reads to the regions flanking gaps. Then those reads that map to these regions can be scanned to identify the Chromium barcodes that represent the molecules sequenced from these gap regions. Extracting reads with shared barcodes and feeding them into Supernova could produce the long reads for approach 1, as is described [here](https://kb.10xgenomics.com/hc/en-us/articles/360002271892-Is-there-a-way-to-fill-in-a-gap-in-our-Supernova-assembly-that-falls-within-our-region-of-interest-). These long reads can then be passed to cobbler.

Something similar can be performed with Sealer, where for a given gap, the reads are mapped to the flanks to identify the Chromium barcodes for that region. Reads with those barcodes can then be extracted and fed into Sealer. So this could be a work-around that helps to take advantage of the long-range information by restricting the reads used to fill a gap to those likely to originate from that region of the genome. I also suspect this would be a bit more computationally efficient.

With both approaches, it seems one would have to write some scripts to run through this process individually on each gap.

Do either, or both, of these approaches seem feasible? I have some work ahead of me to implement either, but was hoping to get some feedback from someone far more knowledgeable about these tools/data before giving it a shot.

Thanks!
Daren

**Comment by warrenlr** [comment] 2019-06-19 23:22
you're welcome!

Yes, both are feasible I think :)

I experimented with 1) a while ago but with limited success at the time. Then, we had modified ARCS to output all barcodes of given gaps, then assemble their constituent reads. This only worked when the physical [molecule] coverage over the gap was sufficient, because each molecule has <1X sequence coverage.  Other limitation of such a strategy concerns barcode reuse; it confounds the assembly since each barcode is shared by ~10 molecules in a typical linked read/Chromium human data.

Since, we have been working on strategies to deconvolute the barcodes into discrete molecules, which would make it possible to perform targeted gap-filling approaches, and other applications. These  strategies will be presented at ISMB2019 in July.

Best,
Rene

**Comment by ckeeling** [comment] 2019-06-20 14:26
Thanks for the description of your recommended order of doing things @warrenlr .  It was very helpful for me too.
Regards,
Chris

**Comment by warrenlr** [comment] 2019-06-20 17:59
[BTLWGAstrategies_v0.2_20jun2019.pdf](https://github.com/bcgsc/RAILS/files/3311557/BTLWGAstrategies_v0.2_20jun2019.pdf)

Above a flow chart of data flow, fyi.  In some case, and depending on data availability, you may re-run tools (or run them iteratively) in a pipeline.  This is only provided as a general guide.  Some tools have been omitted for flowchart clarity.

**Comment by warrenlr** [comment] 2019-06-20 18:00
![BTLWGAstrategies_v0 2_20jun2019](https://user-images.githubusercontent.com/5719157/59870555-9947e700-934a-11e9-8244-90daeb7d4f2d.png)

Above a flow chart of data flow, fyi. In some case, and depending on data availability, you may re-run tools (or run them iteratively) in a pipeline. This is only provided as a general guide. Some tools have been omitted for flowchart clarity.

**Comment by warrenlr** [comment] 2019-06-20 18:01
you're welcome @ckeeling !

**Closed** 2020-01-02 03:35 UTC
Labels: help wanted, question
